title: sysext-bakery 
description: sysext-bakery documentation
baseurl: "/sysext-bakery"
url: "https://flatcar.github.io"
permalink: /:title/
markdown: kramdown

remote_theme: just-the-docs/just-the-docs@v0.10.1
plugins:
  - jekyll-remote-theme
